version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: app
    develop:
      watch:
      - action: rebuild
        files:
        - ./**/*.go
        - ./go.mod
        - ./go.sum
    ports:
    - "8080:8080"
